### ISSUE TITLE
Text detection is failed (EasyOCREngine) 

### ISSUE THREAD

**Issue by kkkuraga** [Danily07/Translumo#125]
Hello, in the new version 0.9.6 I encountered a problem: Text detection is failed (EasyOCREngine)
I reinstalled the program several times, it didn’t help, I looked for a solution to this problem from other users, but unfortunately the problem remained 
Win10Pro
CPU  AMD Ryzen 7 4800H
RAM  8GB
I will attach logs  
[log20240430.txt](https://github.com/Danily07/Translumo/files/15168621/log20240430.txt)

**Comment by PSR2144-3933** [comment]
i met a similar problem
[log20240715.txt](https://github.com/user-attachments/files/16228254/log20240715.txt)
neither reinstall pytorch/easyocr/vcredist nor restart Translumo works

**Comment by PSR2144-3933** [comment]
btw each time i turn off and turn on EasyOCR in text recognition "Required python module are not installed" appears
after the install completed, a error would appear in log
01:38:41.961 [ERR] EasyOCR initialization error
Python.Runtime.PythonException: [WinError 126] The specified module could not be found. Error loading "D:\Utility\Translumo-v.0.9.6\Python\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
  File "D:\Utility\Translumo-v.0.9.6\Python\lib\site-packages\torch\__init__.py", line 143, in <module>
    raise err
  File "D:\Utility\Translumo-v.0.9.6\Python\lib\site-packages\easyocr\recognition.py", line 2, in <module>
    import torch
  File "D:\Utility\Translumo-v.0.9.6\Python\lib\site-packages\easyocr\easyocr.py", line 3, in <module>
    from .recognition import get_recognizer, get_text
  File "D:\Utility\Translumo-v.0.9.6\Python\lib\site-packages\easyocr\__init__.py", line 1, in <module>
    from .easyocr import Reader
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.NewReferenceExtensions.BorrowOrThrow(NewReference& reference)
   at Python.Runtime.PyModule.Import(String name)
   at Python.Runtime.Py.Import(String name)
   at Translumo.Infrastructure.Python.PythonEngineWrapper.Import(String libName)
   at Translumo.OCR.EasyOCR.EasyOCREngine.<InitializeObjects>b__22_0()
   at Translumo.Infrastructure.Python.PythonEngineWrapper.<>c__DisplayClass5_0.<Execute>b__0()
   at Translumo.Infrastructure.Python.PythonEngineWrapper.Execute[T](Func`1 func)
   at Translumo.Infrastructure.Python.PythonEngineWrapper.Execute(Action action)
   at Translumo.OCR.EasyOCR.EasyOCREngine.InitializeObjects()
   at Translumo.OCR.EasyOCR.EasyOCREngine.EnsureInitialized()

**Comment by PSR2144-3933** [comment]
nah symbolic link to another python install don't work
really need support

**Comment by PSR2144-3933** [comment]
(EasyOCR is still ticked when this exception happens
![QQ_1720980094892](https://github.com/user-attachments/assets/64b23558-a88e-4975-920a-24f9aed17738)

**Comment by Eclassic32** [comment]
Same error with me 
[log20241003.txt](https://github.com/user-attachments/files/17246612/log20241003.txt)

OS: Windows 10 Enterprise 22H2
CPU: AMD Ryzen 5 3600 6-Core Processor @ 3.59 GHz
RAM: 16 GB
Graphic Card: NVIDIA GeForce RTX 3050

**Comment by thuanvo2405** [comment]
I had the same issue on Windows 11.

The application failed with:

`System.DllNotFoundException: Could not load ...\python38.dll (Win32Exception 126)`

In my case, the fix was installing the **Microsoft Visual C++ Redistributable 2015–2022** (x64). After installing it and restarting Windows, Translumo started working correctly.

Hopefully this helps anyone else running into the same problem.

**Comment by tuan23590** [comment]
### 💡 Quick fix for `AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'`

If you are experiencing crashes with `EasyOCREngine` due to the Pillow library update, here is how to fix it manually without downgrading any packages:

1. Navigate to your Translumo Python directory:
   `...\Translumo_1.0.2\Python\lib\site-packages\easyocr\`
2. Open the file **`utils.py`** in a text editor (e.g., Notepad).
3. Search for the keyword `Image.ANTIALIAS`. You will find **two instances** of it in this file.
4. Replace **both** instances of `Image.ANTIALIAS` with `Image.Resampling.LANCZOS`.
5. Save the file and restart Translumo. 

This error occurs because `ANTIALIAS` was completely removed in Pillow v10.0.0. Replacing both occurrences with `Resampling.LANCZOS` fully resolves the text detection crash!
