### ISSUE TITLE
 [ERR] Screen capture failed (code: -2005270489) 

### ISSUE THREAD

**Issue by Quebber1** [Danily07/Translumo#174]
I've tried everything I know but it always gives this error in logs and doesn't do anything.

12:06:54.513 [ERR] Screen capture failed (code: -2005270489)
Translumo.Processing.Exceptions.CaptureException: Failed to acquire frame
   at Translumo.Services.ScreenDXCapturer.MakeScreenshotInternal(RectangleF captureArea, Int32 curAttempt)
   at Translumo.Services.ScreenDXCapturer.MakeScreenshotInternal(RectangleF captureArea, Int32 curAttempt)
   at Translumo.Services.ScreenDXCapturer.MakeScreenshotInternal(RectangleF captureArea, Int32 curAttempt)
   at Translumo.Services.ScreenDXCapturer.MakeScreenshotInternal(RectangleF captureArea, Int32 curAttempt)
   at Translumo.Services.ScreenDXCapturer.MakeScreenshotInternal(RectangleF captureArea, Int32 curAttempt)
   at Translumo.Services.ScreenDXCapturer.CaptureScreen()
   at Translumo.Processing.TranslationProcessingService.TranslateInternal(CancellationToken cancellationToken)

**Comment by x4tz1s** [comment]
Did you find solution?

**Comment by Minyzuka** [comment]
bonjour même problème. 
une solution ?

**Comment by LVSZSR** [comment]
run as administrator

**Comment by ramjke** [comment]
It’s probably because the target window is running as an administrator, so you need to run Translumo from admin for this case as well. Closing this issue for now. If you have any updates, please create a new issue.
