### ISSUE TITLE
EasyOCR не устанавливается

### ISSUE THREAD

**Issue by serrrj** [Danily07/Translumo#18]
Не работает ни в обычном режиме с правами администратора, ни под впном. Пытается долгое время установить pytorch, затем закрывается с ошибкой a task was canceled(под впном) и длинным кодом ошибки без впна. Также попробовал самостоятельно поставить недостающие модули - программа их не видит и пытается установить их самостоятельно

**Comment by Danily07** [comment]
если приложение не видит модули после самостоятельной установки, то, вероятно, они у вас глобально на систему установились (если там есть развернутый python).
Попробуйте установить таким образом:
Из **директории с приложением и подпапки Python** выполнить след. команды в cmd:
`.\python.exe .\scripts\pip.exe install torch torchvision --index-url https://download.pytorch.org/whl/cu118`
и 
`.\python.exe .\scripts\pip.exe install easyocr==1.6.2`

**Comment by serrrj** [comment]
Спасибо

**Comment by hikkachannel** [comment]
Есть та же проблема с невозможностью установки EasyOCR из окна настроек. Попробовал воспользоваться командами выше, имею такую ошибку. 

```
  Downloading https://download.pytorch.org/whl/cu118/torch-2.1.1%2Bcu118-cp38-cp38-win_amd64.whl (2722.8 MB)
     ------ --------------------------------- 0.4/2.7 GB 1.6 MB/s eta 0:23:39
ERROR: Exception:
Traceback (most recent call last):
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in _fp_read
    data = self._fp.read(chunk_amt)
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
  File "http\client.py", line 454, in read
  File "http\client.py", line 498, in readinto
  File "socket.py", line 669, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 211, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
    super().__init__(
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\operations\prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\operations\prepare.py", line 596, in _prepare_linked_requirement
    local_file = unpack_url(
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\operations\prepare.py", line 168, in unpack_url
    file = get_http_url(
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\operations\prepare.py", line 109, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_vendor\urllib3\response.py", line 587, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "contextlib.py", line 131, in __exit__
  File "D:\TRANSLUMO\Python\lib\site-packages\pip\_vendor\urllib3\response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None)", ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
```

**Comment by Danily07** [comment]
@hikkachannel под VPN пробовали устанавливать (в т.ч. из консоли)?

**Comment by hikkachannel** [comment]
> @hikkachannel под VPN пробовали устанавливать (в т.ч. из консоли)?

Да, все равно дропает на рандомном моменте загрузку.
Есть мб возможность мануально установить его?

**Comment by Danily07** [comment]
Можете  попробовать вручную скачать файл `https://download.pytorch.org/whl/cu118/torch-2.1.1%2Bcu118-cp38-cp38-win_amd64.whl` и указать его в первой команде, что то вроде:
`.\python.exe .\scripts\pip.exe install C:/some-folder/torch-2.1.1+cu118-cp38-cp38-win_amd64.whl` (подставить свой путь)
и вторую команду выполнить без изменений
