### ISSUE TITLE
WinOCR и запуск не от Администратора

### ISSUE THREAD

**Issue by Vladonai** [Danily07/Translumo#37]
Описание проблемы: запускаю программу от Администратора, OCR-движок WinOCR в настройках включён. Запускаю от обычного пользователя - WinOCR в настройках выключен, при попытке включить требует повышения уровня до Администратора. При этом все нужные пакеты уже скачены и из-под Администратора всё работает. Но галку в настройках из-под обычного пользователя не поставить.

Я ставил программу кажется ещё со второго релиза, а дальше только исполняемый файл обновлял. Возможно при установке с нуля это уже не так, но у меня так. А хотелось бы не от Администратора запускать программу.

**Comment by Danily07** [comment]
Т.е. я правильно понимаю, что настройки после перезапуска приложения не сохраняются (т.е. WinOCR был включен -> перезапустили не под администратором и он оказался выключен)

**Comment by Vladonai** [comment]
> Т.е. я правильно понимаю, что настройки после перезапуска приложения не сохраняются (т.е. WinOCR был включен -> перезапустили не под администратором и он оказался выключен)?

Да.

**Comment by Danily07** [comment]
Попробуйте удалить файл настроек из Users/<Пользователь>/AppData/Roaming/Translumo/settings, затем запустить приложение, включить winocr и переоткрыть вновь не под администратором

**Comment by Vladonai** [comment]
> Попробуйте удалить файл настроек из Users/<Пользователь>/AppData/Roaming/Translumo/settings, затем запустить приложение, включить winocr и переоткрыть вновь не под администратором

Удалил файл settings, запустил приложение от Администратора, снял-поставил галку на WInOCR, закрыл приложение, запустил вновь от обычного пользователя - настройки сброшены, ни один OCR-движок не выбран - при попытке выбрать WinOCR требует повышения прав. Ну точнее выводит ваше окно о необходимости для установки пакетов запустить программу с правами администратора.

Ну и в логе соответственно:
```

17:52:07.980 [ERR] Checking language pack error
Translumo.Infrastructure.Exceptions.OptionalFeatureAccessException: Failed to get PS object
 ---> System.Runtime.InteropServices.COMException (0x800702E4): Запрошенная операция требует повышения.

   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   --- End of inner exception stack trace ---
   at Translumo.Infrastructure.Powershell.OptionalFeaturesProvider.GetPsObjectOcrLanguagePack(String languageCode)
   at Translumo.Infrastructure.Powershell.OptionalFeaturesProvider.OcrLanguagePackIsInstalled(String languageCode)
   at Translumo.Dialog.Stages.ConditionalInteractionStage.ExecuteInner()
   at Translumo.Dialog.Stages.InteractionStage.ExecuteAsync()

```

Где находится файл settings для Администратора кстати? Что-то не нашёл я его. А то бы попробовал заменить.

**Comment by Danily07** [comment]
Спасибо! А после удаления settings -> открытия заного приложения -> закрытия, заного там файл settings создается? По какой-то причине у вас не сохраняются актуальные пользовательские настройки, пока неясно. 
>  Где находится файл settings для Администратора кстати? Что-то не нашёл я его. А то бы попробовал заменить.
ваш пользователь системы же и так (вероятно) администратор, он вот один и тот же используется

**Comment by Vladonai** [comment]
> Спасибо! А после удаления settings -> открытия заного приложения -> закрытия, заного там файл settings создается?

Если запускаю программу под обычным пользователем, то файл settings создаётся. Если под Администратором, то нет. Но настройки под Администратором где-то хранятся, а вот где - непонятно. И да, строго говоря это просто повышение прав, а не запуск из-под другого пользователя. Эту ситуацию можно воспроизвести и на вашем компьютере. Странно, если она даёт другой результат.

И ещё одна проблема. К сожалению, ошибка с определением изменения текста ушла не совсем. Я просто мало играю в последнее время, но вот поиграл недавно и мой вывод: стало гораздо лучше чем раньше, но проблема всё ещё есть. Довольно часто изменение текста не определяется. Однако поскольку есть явные изменения к лучшему, то дальше улучшать наверное стоит именно в этом направлении.
