### ISSUE TITLE
The term 'Get-WindowsCapability' is not recognized as a name of a cmdlet

### ISSUE THREAD

**Issue by alexpol97** [Danily07/Translumo#45]
При включении второй модели (Windows OCR) вылезает ошибка, в логах следующее:

```
[ERR] Checking language pack error
Translumo.Infrastructure.Exceptions.OptionalFeatureAccessException: Failed to get PS object
 ---> System.Management.Automation.CommandNotFoundException: The term 'Get-WindowsCapability' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandOrigin commandOrigin)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   --- End of inner exception stack trace ---
   at Translumo.Infrastructure.Powershell.OptionalFeaturesProvider.GetPsObjectOcrLanguagePack(String languageCode)
   at Translumo.Infrastructure.Powershell.OptionalFeaturesProvider.OcrLanguagePackIsInstalled(String languageCode)
   at Translumo.Dialog.Stages.ConditionalInteractionStage.ExecuteInner()
   at Translumo.Dialog.Stages.InteractionStage.ExecuteAsync()
```

И, вроде бы, понятно, что не распознается команда Get-WindowsCapability из dism, но как исправить - идей нет.

**Comment by alexpol97** [comment]
Решено удалением лишнего PowerShell 7
